pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
                sh 'javac -encoding UTF-8 -d classes May21/src/**/*.java'
            }
        }
        stage('Test') {
            steps {
				sh 'java -cp classes:May21/lib/junit-platform-console-standalone-1.7.1.jar org.junit.platform.console.ConsoleLauncher --scan-classpath > test_results.txt'            }
        }


    }
    post {
        always {
            archiveArtifacts 'test_results.txt'
        }
        failure {
            echo 'Build or test failed'
            emailext (
            subject: " Build 실패: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
            body: """\
                <p> 빌드 실패</p>
                <p>에러 원인 확인 필요</p>
                <p>빌드 URL: ${env.BUILD_URL}</p>
            """,
            to: "ls01050766@gmail.com"
        )
        }
        success {
            echo 'Build and test succeeded'
            emailext (
            subject: "Build 성공: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
            body: """\
                <p>빌드 성공!</p>
                <p>결과 파일: <a href="${env.BUILD_URL}artifact/test_results.txt">test_results.txt</a></p>
                <p>빌드 URL: ${env.BUILD_URL}</p>
            """,
            to: "ls01050766@gmail.com"
        )
        }
    }
}
